package LogisticsUI;

import javax.swing.ImageIcon;
import datautils.io.*;
import ClassTemplates.*;

public class CustomerRegistration extends javax.swing.JFrame {
    private String customerToRegister;

    public CustomerRegistration(String customerToRegister) {
        initComponents();
        this.customerToRegister = customerToRegister;
        setIconImage(new ImageIcon("src/assets/truck.png").getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeReg = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        tagline = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        regForm = new javax.swing.JPanel();
        regHeading = new javax.swing.JLabel();
        prompt = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        contactPhone = new javax.swing.JTextField();
        custAddr = new javax.swing.JTextField();
        addr = new javax.swing.JLabel();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DeliverIT | Registration");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        welcomeReg.setBackground(new java.awt.Color(70, 92, 239));
        welcomeReg.setForeground(new java.awt.Color(255, 255, 255));
        welcomeReg.setPreferredSize(new java.awt.Dimension(400, 500));

        heading.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("WELCOME TO");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/deliverit.png"))); // NOI18N

        tagline.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        tagline.setForeground(new java.awt.Color(255, 255, 255));
        tagline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagline.setText("We'll get it there.");

        copyright.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("©2024 | Tarps.tech");

        javax.swing.GroupLayout welcomeRegLayout = new javax.swing.GroupLayout(welcomeReg);
        welcomeReg.setLayout(welcomeRegLayout);
        welcomeRegLayout.setHorizontalGroup(
            welcomeRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeRegLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(welcomeRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeRegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(welcomeRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagline, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );
        welcomeRegLayout.setVerticalGroup(
            welcomeRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeRegLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(heading)
                .addGap(98, 98, 98)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(61, 61, 61))
        );

        jPanel1.add(welcomeReg);
        welcomeReg.setBounds(0, 0, 400, 500);

        regForm.setBackground(new java.awt.Color(255, 255, 255));
        regForm.setPreferredSize(new java.awt.Dimension(400, 500));

        regHeading.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        regHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regHeading.setText("Register");

        prompt.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        prompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prompt.setText("Enter important details below.");

        name.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        name.setText("Name");

        custName.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        custName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        custName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        phone.setText("Contact No.");

        contactPhone.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        contactPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        contactPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactPhoneActionPerformed(evt);
            }
        });

        custAddr.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        custAddr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        custAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddrActionPerformed(evt);
            }
        });

        addr.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        addr.setText("Address");

        register.setBackground(new java.awt.Color(70, 92, 239));
        register.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regFormLayout = new javax.swing.GroupLayout(regForm);
        regForm.setLayout(regFormLayout);
        regFormLayout.setHorizontalGroup(
            regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regFormLayout.createSequentialGroup()
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regFormLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(regHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regFormLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regFormLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone)
                            .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        regFormLayout.setVerticalGroup(
            regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regFormLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(regHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.add(regForm);
        regForm.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameActionPerformed

    private void contactPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactPhoneActionPerformed

    private void custAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAddrActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String name = custName.getText(), contact = contactPhone.getText(), address = custAddr.getText();
        Customer customer = new Customer(CSVParser.getLatestID("src/CSVFiles/customers.csv") + 1, name, contact, address);
        CSVParser.saveEntry(customer.toCSVFormat(), "src/CSVFiles/customers.csv");
        this.dispose();
        new CustomerDashboard(customer);
    }//GEN-LAST:event_registerActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addr;
    private javax.swing.JTextField contactPhone;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField custAddr;
    private javax.swing.JTextField custName;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel prompt;
    private javax.swing.JPanel regForm;
    private javax.swing.JLabel regHeading;
    private javax.swing.JButton register;
    private javax.swing.JLabel tagline;
    private javax.swing.JPanel welcomeReg;
    // End of variables declaration//GEN-END:variables
}
