package LogisticsUI;
import ClassTemplates.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class CustomerDashboard extends javax.swing.JFrame {
    private Customer customerLoggedIn;

    public CustomerDashboard(Customer customerLoggedIn) {
        initComponents();
        this.customerLoggedIn = customerLoggedIn;
        setIconImage(new ImageIcon("src/assets/truck.png").getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        // TODO: Load Customer shipments and information
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutPanel = new javax.swing.JPanel();
        sideBarLayout = new javax.swing.JPanel();
        helloHeader = new javax.swing.JLabel();
        customerLoggedInName = new javax.swing.JLabel();
        sendPkgBtn = new javax.swing.JButton();
        acctBtn = new javax.swing.JButton();
        shipmentBtn = new javax.swing.JButton();
        signOutBtn1 = new javax.swing.JButton();
        parentCardPanel = new javax.swing.JPanel();
        sendPackagePanel = new javax.swing.JPanel();
        accountsPanel = new javax.swing.JPanel();
        editPanelForm = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneFld = new javax.swing.JTextField();
        addrLbl = new javax.swing.JLabel();
        addrFld = new javax.swing.JTextField();
        nameEditBtn = new javax.swing.JButton();
        phoneEditBtn = new javax.swing.JButton();
        addrEditBtn = new javax.swing.JButton();
        infoHdr = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        shipmentsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DeliverIT | Customer Dashboard");
        setResizable(false);

        layoutPanel.setForeground(new java.awt.Color(70, 92, 239));
        layoutPanel.setLayout(null);

        sideBarLayout.setBackground(new java.awt.Color(70, 92, 239));
        sideBarLayout.setMinimumSize(new java.awt.Dimension(200, 500));
        sideBarLayout.setPreferredSize(new java.awt.Dimension(200, 500));

        helloHeader.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        helloHeader.setForeground(new java.awt.Color(255, 255, 255));
        helloHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloHeader.setText("Hello");

        customerLoggedInName.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        customerLoggedInName.setForeground(new java.awt.Color(255, 255, 255));
        customerLoggedInName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLoggedInName.setText("Customer!");

        sendPkgBtn.setBackground(new java.awt.Color(70, 92, 239));
        sendPkgBtn.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        sendPkgBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendPkgBtn.setText("Send Package");
        sendPkgBtn.setBorder(null);
        sendPkgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sendPkgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPkgBtnActionPerformed(evt);
            }
        });

        acctBtn.setBackground(new java.awt.Color(70, 92, 239));
        acctBtn.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        acctBtn.setForeground(new java.awt.Color(255, 255, 255));
        acctBtn.setText("My Account");
        acctBtn.setBorder(null);
        acctBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctBtnActionPerformed(evt);
            }
        });

        shipmentBtn.setBackground(new java.awt.Color(70, 92, 239));
        shipmentBtn.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        shipmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        shipmentBtn.setText("My Shipments");
        shipmentBtn.setBorder(null);
        shipmentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipmentBtnActionPerformed(evt);
            }
        });

        signOutBtn1.setBackground(new java.awt.Color(0, 0, 204));
        signOutBtn1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        signOutBtn1.setForeground(new java.awt.Color(255, 255, 255));
        signOutBtn1.setText("Sign Out");
        signOutBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 0, 255), new java.awt.Color(102, 51, 255)));
        signOutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayoutLayout = new javax.swing.GroupLayout(sideBarLayout);
        sideBarLayout.setLayout(sideBarLayoutLayout);
        sideBarLayoutLayout.setHorizontalGroup(
            sideBarLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerLoggedInName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(acctBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sendPkgBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helloHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideBarLayoutLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(signOutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        sideBarLayoutLayout.setVerticalGroup(
            sideBarLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayoutLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(helloHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerLoggedInName)
                .addGap(50, 50, 50)
                .addComponent(sendPkgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(signOutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        layoutPanel.add(sideBarLayout);
        sideBarLayout.setBounds(0, 0, 200, 500);

        parentCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        parentCardPanel.setLayout(new java.awt.CardLayout());

        sendPackagePanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout sendPackagePanelLayout = new javax.swing.GroupLayout(sendPackagePanel);
        sendPackagePanel.setLayout(sendPackagePanelLayout);
        sendPackagePanelLayout.setHorizontalGroup(
            sendPackagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        sendPackagePanelLayout.setVerticalGroup(
            sendPackagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        parentCardPanel.add(sendPackagePanel, "card2");

        accountsPanel.setBackground(new java.awt.Color(240, 245, 255));

        editPanelForm.setBackground(new java.awt.Color(255, 255, 255));

        nameLbl.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        nameLbl.setText("Name");

        nameFld.setEnabled(false);

        phoneLbl.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        phoneLbl.setText("Phone Number");

        phoneFld.setEnabled(false);

        addrLbl.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        addrLbl.setText("Address");

        addrFld.setEnabled(false);

        nameEditBtn.setBackground(new java.awt.Color(73, 204, 112));
        nameEditBtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        nameEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        nameEditBtn.setText("Edit");
        nameEditBtn.setBorderPainted(false);
        nameEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEditBtnActionPerformed(evt);
            }
        });

        phoneEditBtn.setBackground(new java.awt.Color(73, 204, 112));
        phoneEditBtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        phoneEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        phoneEditBtn.setText("Edit");
        phoneEditBtn.setBorderPainted(false);

        addrEditBtn.setBackground(new java.awt.Color(73, 204, 112));
        addrEditBtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        addrEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        addrEditBtn.setText("Edit");
        addrEditBtn.setBorderPainted(false);

        javax.swing.GroupLayout editPanelFormLayout = new javax.swing.GroupLayout(editPanelForm);
        editPanelForm.setLayout(editPanelFormLayout);
        editPanelFormLayout.setHorizontalGroup(
            editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameFld)
                    .addComponent(phoneFld, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(addrFld, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addrLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addrEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        editPanelFormLayout.setVerticalGroup(
            editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelFormLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(phoneLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(phoneFld))
                .addGap(18, 18, 18)
                .addComponent(addrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addrEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(addrFld))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        infoHdr.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        infoHdr.setText("My Information");

        saveBtn.setBackground(new java.awt.Color(70, 92, 239));
        saveBtn.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setBorderPainted(false);

        javax.swing.GroupLayout accountsPanelLayout = new javax.swing.GroupLayout(accountsPanel);
        accountsPanel.setLayout(accountsPanelLayout);
        accountsPanelLayout.setHorizontalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoHdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        accountsPanelLayout.setVerticalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(infoHdr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        parentCardPanel.add(accountsPanel, "card3");

        shipmentsPanel.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout shipmentsPanelLayout = new javax.swing.GroupLayout(shipmentsPanel);
        shipmentsPanel.setLayout(shipmentsPanelLayout);
        shipmentsPanelLayout.setHorizontalGroup(
            shipmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        shipmentsPanelLayout.setVerticalGroup(
            shipmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        parentCardPanel.add(shipmentsPanel, "card4");

        layoutPanel.add(parentCardPanel);
        parentCardPanel.setBounds(200, 0, 610, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendPkgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPkgBtnActionPerformed
        parentCardPanel.removeAll();
        parentCardPanel.add(sendPackagePanel);
        parentCardPanel.repaint();
        parentCardPanel.revalidate();
    }//GEN-LAST:event_sendPkgBtnActionPerformed

    private void acctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctBtnActionPerformed
        parentCardPanel.removeAll();
        parentCardPanel.add(accountsPanel);
        parentCardPanel.repaint();
        parentCardPanel.revalidate();
    }//GEN-LAST:event_acctBtnActionPerformed

    private void shipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipmentBtnActionPerformed
        parentCardPanel.removeAll();
        parentCardPanel.add(shipmentsPanel);
        parentCardPanel.repaint();
        parentCardPanel.revalidate();
    }//GEN-LAST:event_shipmentBtnActionPerformed

    private void nameEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEditBtnActionPerformed

    private void signOutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JButton acctBtn;
    private javax.swing.JButton addrEditBtn;
    private javax.swing.JTextField addrFld;
    private javax.swing.JLabel addrLbl;
    private javax.swing.JLabel customerLoggedInName;
    private javax.swing.JPanel editPanelForm;
    private javax.swing.JLabel helloHeader;
    private javax.swing.JLabel infoHdr;
    private javax.swing.JPanel layoutPanel;
    private javax.swing.JButton nameEditBtn;
    private javax.swing.JTextField nameFld;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JPanel parentCardPanel;
    private javax.swing.JButton phoneEditBtn;
    private javax.swing.JTextField phoneFld;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel sendPackagePanel;
    private javax.swing.JButton sendPkgBtn;
    private javax.swing.JButton shipmentBtn;
    private javax.swing.JPanel shipmentsPanel;
    private javax.swing.JPanel sideBarLayout;
    private javax.swing.JButton signOutBtn1;
    // End of variables declaration//GEN-END:variables
}
