/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LogisticsUI;

import datautils.io.CSVParser;
import java.awt.CardLayout;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class WarehouseManager extends javax.swing.JFrame {
    
    private final java.awt.Color defaultButtonColor = java.awt.Color.decode("#465CEF");
    private final java.awt.Color activeButtonColor = java.awt.Color.decode("#509BE5");
    /**
     * Creates new form WarehouseManager
     */
    public WarehouseManager() {
        initComponents();
    }
    
    private void resetButtonColors() {
        DropOffBtn.setOpaque(false);
        DropOffBtn.setBackground(defaultButtonColor);
        LoadPackagesBtn.setOpaque(false);
        LoadPackagesBtn.setBackground(defaultButtonColor);
        ManageVehiclesBtn.setOpaque(false);
        ManageVehiclesBtn.setBackground(defaultButtonColor);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NullPanel = new javax.swing.JPanel();
        SidebarPanel = new javax.swing.JPanel();
        UserGreetingsLabel = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        DropOffBtn = new javax.swing.JButton();
        LoadPackagesBtn = new javax.swing.JButton();
        ManageVehiclesBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        EmptyPanel = new javax.swing.JPanel();
        LoadPackagesPanel = new javax.swing.JPanel();
        NestedPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailableVehiclesTable = new javax.swing.JTable();
        ConfirmBtn = new javax.swing.JButton();
        DestinationTxtField = new javax.swing.JTextField();
        DestinationLabel = new javax.swing.JLabel();
        VehicleTypeLabel = new javax.swing.JLabel();
        VehicleTypeComboBox = new javax.swing.JComboBox<>();
        DropOffPanel = new javax.swing.JPanel();
        NestedPanel1 = new javax.swing.JPanel();
        HeaderLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DropOffVehicleListTable = new javax.swing.JTable();
        ConfirmBtn2 = new javax.swing.JButton();
        ManageVehiclesPanel = new javax.swing.JPanel();
        NestedPanel3 = new javax.swing.JPanel();
        HeaderLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AvailableVehiclesTable1 = new javax.swing.JTable();
        ConfirmBtn1 = new javax.swing.JButton();
        VehicleActionLabel = new javax.swing.JLabel();
        VehicleActionComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        NullPanel.setBackground(new java.awt.Color(240, 245, 255));
        NullPanel.setLayout(null);

        SidebarPanel.setBackground(new java.awt.Color(70, 92, 239));
        SidebarPanel.setMaximumSize(new java.awt.Dimension(200, 500));
        SidebarPanel.setMinimumSize(new java.awt.Dimension(200, 500));

        UserGreetingsLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserGreetingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserGreetingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserGreetingsLabel.setText("<html><span style='font-family:Inter; font-weight:bold;'>Hello, </span><span style='font-family:Inter; font-weight:50;'>Manager</span></html>");

        Logout.setBackground(new java.awt.Color(80, 155, 229));
        Logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("<html>   <body style=\"font-family: Inter; font-weight: 600; text-align: center;\">     Logout   </body> </html> ");
        Logout.setBorderPainted(false);
        Logout.setFocusPainted(false);
        Logout.setFocusable(false);
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout.setRequestFocusEnabled(false);
        Logout.setRolloverEnabled(false);
        Logout.setVerifyInputWhenFocusTarget(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        DropOffBtn.setBackground(new java.awt.Color(70, 92, 239));
        DropOffBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DropOffBtn.setForeground(new java.awt.Color(255, 255, 255));
        DropOffBtn.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Drop-Off<br>Vehicle Load</body></html>");
        DropOffBtn.setActionCommand("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Drop-Off<br>Vehicle Load</body></html>");
        DropOffBtn.setBorderPainted(false);
        DropOffBtn.setContentAreaFilled(false);
        DropOffBtn.setFocusPainted(false);
        DropOffBtn.setFocusable(false);
        DropOffBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DropOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropOffBtnActionPerformed(evt);
            }
        });

        LoadPackagesBtn.setBackground(new java.awt.Color(70, 92, 239));
        LoadPackagesBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LoadPackagesBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoadPackagesBtn.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Load Packages<br>by Destination</body></html>");
        LoadPackagesBtn.setBorderPainted(false);
        LoadPackagesBtn.setContentAreaFilled(false);
        LoadPackagesBtn.setFocusPainted(false);
        LoadPackagesBtn.setFocusable(false);
        LoadPackagesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoadPackagesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadPackagesBtnActionPerformed(evt);
            }
        });

        ManageVehiclesBtn.setBackground(new java.awt.Color(70, 92, 239));
        ManageVehiclesBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ManageVehiclesBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageVehiclesBtn.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Manage<br>Vehicles</body></html>");
        ManageVehiclesBtn.setBorderPainted(false);
        ManageVehiclesBtn.setContentAreaFilled(false);
        ManageVehiclesBtn.setFocusPainted(false);
        ManageVehiclesBtn.setFocusable(false);
        ManageVehiclesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageVehiclesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageVehiclesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarPanelLayout = new javax.swing.GroupLayout(SidebarPanel);
        SidebarPanel.setLayout(SidebarPanelLayout);
        SidebarPanelLayout.setHorizontalGroup(
            SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(UserGreetingsLabel)
            .addGroup(SidebarPanelLayout.createSequentialGroup()
                .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoadPackagesBtn)
                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                        .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DropOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageVehiclesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SidebarPanelLayout.setVerticalGroup(
            SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(UserGreetingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(LoadPackagesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DropOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageVehiclesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NullPanel.add(SidebarPanel);
        SidebarPanel.setBounds(0, 0, 200, 500);

        MainPanel.setBackground(new java.awt.Color(240, 245, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        EmptyPanel.setBackground(new java.awt.Color(240, 245, 255));
        EmptyPanel.setLayout(new java.awt.CardLayout());
        MainPanel.add(EmptyPanel, "card2");

        LoadPackagesPanel.setBackground(new java.awt.Color(240, 245, 255));
        LoadPackagesPanel.setLayout(new java.awt.CardLayout());

        NestedPanel.setBackground(new java.awt.Color(255, 255, 255));

        HeaderLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HeaderLabel.setForeground(new java.awt.Color(0, 0, 0));
        HeaderLabel.setText("<html><span style='font-family: Inter; font-weight: bold;'>Load Packages to Vehicle</span></html>");

        AvailableVehiclesTable.setBackground(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable.setForeground(new java.awt.Color(0, 0, 0));
        AvailableVehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Type", "Warehouse ID", "License Plate", "Current Shipments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AvailableVehiclesTable.setCellSelectionEnabled(true);
        AvailableVehiclesTable.setFocusable(false);
        AvailableVehiclesTable.setGridColor(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        AvailableVehiclesTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable.setShowGrid(true);
        AvailableVehiclesTable.getTableHeader().setResizingAllowed(false);
        AvailableVehiclesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(AvailableVehiclesTable);

        ConfirmBtn.setBackground(new java.awt.Color(73, 204, 112));
        ConfirmBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setText("<html>\n  <body style=\"font-family: Inter; font-weight: bold; text-align: center;\">\n    Confirm\n  </body>\n</html>\n");
        ConfirmBtn.setBorderPainted(false);
        ConfirmBtn.setFocusPainted(false);
        ConfirmBtn.setFocusable(false);
        ConfirmBtn.setRequestFocusEnabled(false);
        ConfirmBtn.setRolloverEnabled(false);
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        DestinationTxtField.setBackground(new java.awt.Color(255, 255, 255));
        DestinationTxtField.setForeground(new java.awt.Color(0, 0, 0));
        DestinationTxtField.setCaretColor(new java.awt.Color(255, 255, 255));
        DestinationTxtField.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        DestinationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DestinationLabel.setForeground(new java.awt.Color(0, 0, 0));
        DestinationLabel.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Sort by Destination</body></html>");

        VehicleTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehicleTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        VehicleTypeLabel.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Vehicle Type</body></html>");

        VehicleTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        VehicleTypeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        VehicleTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Van", "Truck" }));

        javax.swing.GroupLayout NestedPanelLayout = new javax.swing.GroupLayout(NestedPanel);
        NestedPanel.setLayout(NestedPanelLayout);
        NestedPanelLayout.setHorizontalGroup(
            NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NestedPanelLayout.createSequentialGroup()
                                .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DestinationTxtField)
                                    .addComponent(DestinationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(VehicleTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(VehicleTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        NestedPanelLayout.setVerticalGroup(
            NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NestedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestinationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        LoadPackagesPanel.add(NestedPanel, "card2");

        MainPanel.add(LoadPackagesPanel, "LoadPackagesPanel");

        DropOffPanel.setBackground(new java.awt.Color(240, 245, 255));
        DropOffPanel.setLayout(new java.awt.CardLayout());

        NestedPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HeaderLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HeaderLabel1.setForeground(new java.awt.Color(0, 0, 0));
        HeaderLabel1.setText("<html><span style='font-family: Inter; font-weight: bold;'>Available Vehicles for Drop-Off</span></html>");

        DropOffVehicleListTable.setBackground(new java.awt.Color(255, 255, 255));
        DropOffVehicleListTable.setForeground(new java.awt.Color(0, 0, 0));
        DropOffVehicleListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Warehouse ID", "License Plate", "Current Shipments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DropOffVehicleListTable.setCellSelectionEnabled(true);
        DropOffVehicleListTable.setFocusable(false);
        DropOffVehicleListTable.setGridColor(new java.awt.Color(255, 255, 255));
        DropOffVehicleListTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        DropOffVehicleListTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        DropOffVehicleListTable.setShowGrid(false);
        DropOffVehicleListTable.getTableHeader().setResizingAllowed(false);
        DropOffVehicleListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(DropOffVehicleListTable);

        ConfirmBtn2.setBackground(new java.awt.Color(73, 204, 112));
        ConfirmBtn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmBtn2.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn2.setText("<html>\n  <body style=\"font-family: Inter; font-weight: bold; text-align: center;\">\n    Confirm\n  </body>\n</html>\n");
        ConfirmBtn2.setBorderPainted(false);
        ConfirmBtn2.setFocusPainted(false);
        ConfirmBtn2.setFocusable(false);
        ConfirmBtn2.setRequestFocusEnabled(false);
        ConfirmBtn2.setRolloverEnabled(false);
        ConfirmBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NestedPanel1Layout = new javax.swing.GroupLayout(NestedPanel1);
        NestedPanel1.setLayout(NestedPanel1Layout);
        NestedPanel1Layout.setHorizontalGroup(
            NestedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(NestedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NestedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HeaderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        NestedPanel1Layout.setVerticalGroup(
            NestedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(HeaderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        DropOffPanel.add(NestedPanel1, "card2");

        MainPanel.add(DropOffPanel, "DropOffPanel");

        ManageVehiclesPanel.setBackground(new java.awt.Color(240, 245, 255));
        ManageVehiclesPanel.setLayout(new java.awt.CardLayout());

        NestedPanel3.setBackground(new java.awt.Color(255, 255, 255));

        HeaderLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HeaderLabel3.setForeground(new java.awt.Color(0, 0, 0));
        HeaderLabel3.setText("<html><span style='font-family: Inter; font-weight: bold;'>Load Packages to Vehicle</span></html>");

        AvailableVehiclesTable1.setBackground(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable1.setForeground(new java.awt.Color(0, 0, 0));
        AvailableVehiclesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Type", "Warehouse ID", "License Plate", "Current Shipments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AvailableVehiclesTable1.setCellSelectionEnabled(true);
        AvailableVehiclesTable1.setFocusable(false);
        AvailableVehiclesTable1.setGridColor(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        AvailableVehiclesTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        AvailableVehiclesTable1.setShowGrid(true);
        AvailableVehiclesTable1.getTableHeader().setResizingAllowed(false);
        AvailableVehiclesTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(AvailableVehiclesTable1);

        ConfirmBtn1.setBackground(new java.awt.Color(73, 204, 112));
        ConfirmBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn1.setText("<html>\n  <body style=\"font-family: Inter; font-weight: bold; text-align: center;\">\n    Confirm\n  </body>\n</html>\n");
        ConfirmBtn1.setBorderPainted(false);
        ConfirmBtn1.setFocusPainted(false);
        ConfirmBtn1.setFocusable(false);
        ConfirmBtn1.setRequestFocusEnabled(false);
        ConfirmBtn1.setRolloverEnabled(false);
        ConfirmBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtn1ActionPerformed(evt);
            }
        });

        VehicleActionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehicleActionLabel.setForeground(new java.awt.Color(0, 0, 0));
        VehicleActionLabel.setText("<html><body style=\"font-family: Inter; font-weight: 10; text-align: center;\">Select Vehicle Action</body></html>");

        VehicleActionComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        VehicleActionComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        VehicleActionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehicle Arriving", "Vehicle Leaving" }));

        javax.swing.GroupLayout NestedPanel3Layout = new javax.swing.GroupLayout(NestedPanel3);
        NestedPanel3.setLayout(NestedPanel3Layout);
        NestedPanel3Layout.setHorizontalGroup(
            NestedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(NestedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NestedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HeaderLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(NestedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VehicleActionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VehicleActionComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        NestedPanel3Layout.setVerticalGroup(
            NestedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NestedPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(HeaderLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(VehicleActionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VehicleActionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        ManageVehiclesPanel.add(NestedPanel3, "card2");

        MainPanel.add(ManageVehiclesPanel, "ManageVehiclesPanel");

        NullPanel.add(MainPanel);
        MainPanel.setBounds(200, 0, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LogoutActionPerformed

    private void DropOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropOffBtnActionPerformed
        resetButtonColors();
        DropOffBtn.setOpaque(true);
        DropOffBtn.setBackground(activeButtonColor);
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DropOffPanel");
    }//GEN-LAST:event_DropOffBtnActionPerformed

    private void LoadPackagesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadPackagesBtnActionPerformed
        resetButtonColors();
        LoadPackagesBtn.setOpaque(true);
        LoadPackagesBtn.setBackground(activeButtonColor);
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "LoadPackagesPanel");
    }//GEN-LAST:event_LoadPackagesBtnActionPerformed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed

    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void ConfirmBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtn2ActionPerformed

    }//GEN-LAST:event_ConfirmBtn2ActionPerformed

    private void ManageVehiclesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageVehiclesBtnActionPerformed
        resetButtonColors();
        ManageVehiclesBtn.setOpaque(true);
        ManageVehiclesBtn.setBackground(activeButtonColor);
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "ManageVehiclesPanel");
    }//GEN-LAST:event_ManageVehiclesBtnActionPerformed

    private void ConfirmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AvailableVehiclesTable;
    private javax.swing.JTable AvailableVehiclesTable1;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JButton ConfirmBtn1;
    private javax.swing.JButton ConfirmBtn2;
    private javax.swing.JLabel DestinationLabel;
    private javax.swing.JTextField DestinationTxtField;
    private javax.swing.JButton DropOffBtn;
    private javax.swing.JPanel DropOffPanel;
    private javax.swing.JTable DropOffVehicleListTable;
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel HeaderLabel1;
    private javax.swing.JLabel HeaderLabel3;
    private javax.swing.JButton LoadPackagesBtn;
    private javax.swing.JPanel LoadPackagesPanel;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageVehiclesBtn;
    private javax.swing.JPanel ManageVehiclesPanel;
    private javax.swing.JPanel NestedPanel;
    private javax.swing.JPanel NestedPanel1;
    private javax.swing.JPanel NestedPanel3;
    private javax.swing.JPanel NullPanel;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JLabel UserGreetingsLabel;
    private javax.swing.JComboBox<String> VehicleActionComboBox1;
    private javax.swing.JLabel VehicleActionLabel;
    private javax.swing.JComboBox<String> VehicleTypeComboBox;
    private javax.swing.JLabel VehicleTypeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
